// flow-typed signature: 80d9aa7246392176e373f68c714fd378
// flow-typed version: <<STUB>>/etch_v^0.10.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'etch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'etch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'etch/dist/component-helpers' {
  declare module.exports: any;
}

declare module 'etch/dist/default-scheduler' {
  declare module.exports: any;
}

declare module 'etch/dist/dom' {
  declare module.exports: any;
}

declare module 'etch/dist/event-listener-props' {
  declare module.exports: any;
}

declare module 'etch/dist/index' {
  declare module.exports: any;
}

declare module 'etch/dist/patch' {
  declare module.exports: any;
}

declare module 'etch/dist/render' {
  declare module.exports: any;
}

declare module 'etch/dist/scheduler-assignment' {
  declare module.exports: any;
}

declare module 'etch/dist/svg-attribute-translations' {
  declare module.exports: any;
}

declare module 'etch/dist/svg-tags' {
  declare module.exports: any;
}

declare module 'etch/dist/update-props' {
  declare module.exports: any;
}

declare module 'etch/lib/component-helpers' {
  declare module.exports: any;
}

declare module 'etch/lib/default-scheduler' {
  declare module.exports: any;
}

declare module 'etch/lib/dom' {
  declare module.exports: any;
}

declare module 'etch/lib/event-listener-props' {
  declare module.exports: any;
}

declare module 'etch/lib/index' {
  declare module.exports: any;
}

declare module 'etch/lib/patch' {
  declare module.exports: any;
}

declare module 'etch/lib/render' {
  declare module.exports: any;
}

declare module 'etch/lib/scheduler-assignment' {
  declare module.exports: any;
}

declare module 'etch/lib/svg-attribute-translations' {
  declare module.exports: any;
}

declare module 'etch/lib/svg-tags' {
  declare module.exports: any;
}

declare module 'etch/lib/update-props' {
  declare module.exports: any;
}

// Filename aliases
declare module 'etch/dist/component-helpers.js' {
  declare module.exports: $Exports<'etch/dist/component-helpers'>;
}
declare module 'etch/dist/default-scheduler.js' {
  declare module.exports: $Exports<'etch/dist/default-scheduler'>;
}
declare module 'etch/dist/dom.js' {
  declare module.exports: $Exports<'etch/dist/dom'>;
}
declare module 'etch/dist/event-listener-props.js' {
  declare module.exports: $Exports<'etch/dist/event-listener-props'>;
}
declare module 'etch/dist/index.js' {
  declare module.exports: $Exports<'etch/dist/index'>;
}
declare module 'etch/dist/patch.js' {
  declare module.exports: $Exports<'etch/dist/patch'>;
}
declare module 'etch/dist/render.js' {
  declare module.exports: $Exports<'etch/dist/render'>;
}
declare module 'etch/dist/scheduler-assignment.js' {
  declare module.exports: $Exports<'etch/dist/scheduler-assignment'>;
}
declare module 'etch/dist/svg-attribute-translations.js' {
  declare module.exports: $Exports<'etch/dist/svg-attribute-translations'>;
}
declare module 'etch/dist/svg-tags.js' {
  declare module.exports: $Exports<'etch/dist/svg-tags'>;
}
declare module 'etch/dist/update-props.js' {
  declare module.exports: $Exports<'etch/dist/update-props'>;
}
declare module 'etch/lib/component-helpers.js' {
  declare module.exports: $Exports<'etch/lib/component-helpers'>;
}
declare module 'etch/lib/default-scheduler.js' {
  declare module.exports: $Exports<'etch/lib/default-scheduler'>;
}
declare module 'etch/lib/dom.js' {
  declare module.exports: $Exports<'etch/lib/dom'>;
}
declare module 'etch/lib/event-listener-props.js' {
  declare module.exports: $Exports<'etch/lib/event-listener-props'>;
}
declare module 'etch/lib/index.js' {
  declare module.exports: $Exports<'etch/lib/index'>;
}
declare module 'etch/lib/patch.js' {
  declare module.exports: $Exports<'etch/lib/patch'>;
}
declare module 'etch/lib/render.js' {
  declare module.exports: $Exports<'etch/lib/render'>;
}
declare module 'etch/lib/scheduler-assignment.js' {
  declare module.exports: $Exports<'etch/lib/scheduler-assignment'>;
}
declare module 'etch/lib/svg-attribute-translations.js' {
  declare module.exports: $Exports<'etch/lib/svg-attribute-translations'>;
}
declare module 'etch/lib/svg-tags.js' {
  declare module.exports: $Exports<'etch/lib/svg-tags'>;
}
declare module 'etch/lib/update-props.js' {
  declare module.exports: $Exports<'etch/lib/update-props'>;
}
